language: swift

sudo: required

os: osx
osx_image: xcode9.2

script:
  - xcodebuild clean build -project SwiftyNats.xcodeproj -scheme SwiftyNats-Package CODE_SIGNING_REQUIRED=NO
  - xcodebuild -project SwiftyNats.xcodeproj -scheme SwiftyNatsPackageTests test
